level2 = function() {
  return [
      new Block(1, 7),
      new Block(2, 7),
      new Block(3, 7),
      new Block(4, 7),
      new Block(5, 7),
      new Block(6, 7),
      new Block(7, 7),
      new Block(1, 0),
      new Block(2, 0),
      new Block(3, 0),
      new Block(4, 0),
      new Block(5, 0),
      new Block(6, 0),
      new Block(7, 0),
      new Block(0, 1),
      new Block(0, 2),
      new Block(0, 3),
      new Block(0, 4),
      new Block(0, 5),
      new Block(0, 6),
      new Block(0, 7),
      new Block(8, 1),
      new Block(8, 2),
      new Block(8, 3),
      new Block(8, 4),
      new Block(8, 5),
      new Block(8, 6),
      new Block(8, 7),
      new Player(4, 4)
  ]
}
